version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      nest-trio:
        patterns:
          - '@nestjs/common'
          - '@nestjs/core'
          - '@nestjs/testing'
        dependency-type: development
        update-types: ['minor', 'patch']
      jest:
        patterns:
          - 'jest'
          - '@types/jest'
          - 'ts-jest'
        dependency-type: development
        update-types: ['minor', 'patch']
      eslint-typescript-eslint:
        patterns:
          - 'eslint'
          - '@eslint/js'
          - '@typescript-eslint/*'
          - 'globals'
        dependency-type: development
        update-types: ['minor', 'patch']
